[package]
name = "meteors"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
reqwest = {version = "0.12.9", features = ["json"]}
serde = "1.0.215"
serenity = "=0.12.4"
tokio = {version = "1.41.1", features = ["macros", "rt-multi-thread"] }
